### PR TITLE
Fix: Allow custom types (fixes #103)

### LINKED ISSUE #103: Allow custom categories
### Subject of the enhancement
I would like to explore how to implement custom categories via JSON config only. We have clients that use categories other than the default document, media, and link.

### Considerations

- How would the schemas be affected? Would AAT users be able to add as many categories as they need?
- If there are a large number of categories, the drawer width may need to be wider.
- Should we just add x amount of generic categories, and course editors / developers can update these as needed? Maybe the ability for up to 10-15 custom categories?
- Backwards compatibility
- Should we use a new flexible structure for the categories in the JSON?

**Current:**
```
  "_resources": {
    "_isEnabled": true,
    "_filterButtons": {
      "all": "All",
      "document": "Document",
      "media": "Media",
      "link": "Link"
    },
    "_filterAria": {
      "allAria": "View all resources",
      "documentAria": "View document resources",
      "mediaAria": "View media resources",
      "linkAria": "View resource links"
    },
```

**Alternative example:**
```
  "_resources": {
    "_isEnabled": true,
    "_resourcesTypes": [
      {
        "buttonText": "All",
        "ariaLabel": "View all resources",
        "_type": "all"
      },
      {
        "buttonText": "Media",
        "ariaLabel": "View media resources",
        "_type": "media"
      },
      {
        "buttonText": "Document",
        "ariaLabel": "View document resources",
        "_type": "document"
      },
      {
        "buttonText": "Link",
        "ariaLabel": "View resource links",
        "_type": "link"
      }
    ],
```

### PR DESCRIPTION
**Pull request by swashbuck**
Fixes #103 

### Fix
* Adds the ability for custom types
* When using more than the default 4 types, a class of `has-extra-types` is added
* Schema updates

### Testing
1. Add custom categories according to _example.json_
2. Open the Resources drawer and behold the custom type buttons

### Potential additional enhancements
Suggested changes to the Vanilla theme (will require a new ticket / PR):

1. Reduce font size and padding when using extra custom types.
```
.resources__filter.has-extra-types {
  .resources__filter-btn {
    font-size: 0.75rem;
    padding: (@item-padding / 2) (@item-padding / 2);
  }
}
```
2. Remove style that removes the border from the last item.

### Screenshots
These screenshots show the maximum number of categories including the default ones.

With Vanilla changes to font size and padding:

### CODE REVIEW

File: js/adapt-contrib-resources.js [hunk 1]
```diff
@@ -46,9 +46,25 @@ class Resources extends Backbone.Controller {
...
+
+    const customTypes = [];
+    for (let i = 1; i <= 10; i++) {
+      customTypes.push(`custom${i}`);
+    }
+
+    const types = defaultTypes.concat(customTypes);
+
+    model.set('_resourceTypes', types);
+  }
```
Comment (StuartNicholls) [inline js/adapt-contrib-resources.js:67]: @swashbuck is this the correct commit? Just wondering why this is hardcoded here? Maybe pass though resourceData and use that? Something along these lines? 

```
  setupTypes(model, resourcesData) {
    const defaultTypes = ['all']; // must contain 'all'

    const customTypes = [];
    for (let i = 1; i <= resourcesData._resourcesItems.length; i++) {
      customTypes.push(resourcesData._resourcesItems[i]._type);
    }

    const types = defaultTypes.concat(customTypes);
    
    model.set('_resourceTypes', types);
  }
```

File: example.json [hunk 2]
```diff
@@ -11,14 +11,34 @@
...
+            "custom1": "Custom category 1",
+            "custom2": "Custom category 2",
+            "custom3": "Custom category 3",
+            "custom4": "Custom category 4",
+            "custom5": "Custom category 5",
+            "custom6": "Custom category 6",
+            "custom7": "Custom category 7",
+            "custom8": "Custom category 8",
+            "custom9": "Custom category 9",
+            "custom10": "Custom category 10"
```
Comment (StuartNicholls) [inline example.json:24]: Might be worth adding these to the _resourcesItems node too, it threw me off at first!

Comment (swashbuck) [reply example.json:24]: @StuartNicholls I've added an example of using the "custom1" category. That probably gets the idea across?

Comment (StuartNicholls) [reply example.json:24]: Yeah, lovely

File: js/adapt-contrib-resources.js [hunk 3]
```diff
@@ -46,9 +46,27 @@ class Resources extends Backbone.Controller {
         resources = resources.filter(resource => resource._isGlobal !== false);
       }
       model.set('_resources', resources);
+
+      this.setupTypes(model);
```
Comment (StuartNicholls) [inline js/adapt-contrib-resources.js:50]: I think you need to pass though resourceData here

File: js/adapt-contrib-resources.js [hunk 4]
```diff
@@ -46,9 +46,27 @@ class Resources extends Backbone.Controller {
...
+
       drawer.triggerCustomView(new ResourcesView({ model }).$el);
     });
   }
+
+  setupTypes(model, resourcesData) {
+    const types = ['all']; // must contain 'all'
+
+    resourcesData._filterButtons.forEach((e, i) => {
```
Comment (StuartNicholls) [inline js/adapt-contrib-resources.js:59]: Is this a non-array object here? As it doesn't seem to work, even with the above

**Review by StuartNicholls — APPROVED** [review]

**Review by StuartNicholls — APPROVED** [review]

**Review by joe-replin — APPROVED** [review]
👀

File: js/adapt-contrib-resources.js [hunk 5]
```diff
@@ -46,9 +46,28 @@ class Resources extends Backbone.Controller {
...
+    for (const key in filterButtons) {
+      const typeName = key;
+
+      if (typeName !== 'all') {
+        types.push(typeName);
+      }
+    };
+
+    model.set('_resourceTypes', types);
+  }
```
Comment (oliverfoster) [inline js/adapt-contrib-resources.js:69]:
```suggestion
  setupTypes(model, resourcesData) {
    const configuredTypes = Object.keys(resourcesData._filterButtons).filter(type=> type !== 'all');
    const allTypes = [ 'all', ...configuredTypes ];
    model.set('_resourceTypes', allTypes);
  }
```

```js

```
Rather that iterating, try using these:
[`Object.keys`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/keys),[`Object.values`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/values),[`Object.entries`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/entries)
[`... spread syntax`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Spread_syntax#spread_in_array_literals)

The oddity of what's actually happening here is a little clearer when the main focus isn't a loop.
1. Get keys from configured buttons
2. Filter to remove `all`
3. Add `all` to the front
4. Set on the model

Otherwise a `continue` early, similar to `return` early works to reduce the nesting:
```js
    for (const typeName in filterButtons) {
      if (typeName === 'all') continue;
      types.push(typeName);
    }
```

**Review by oliverfoster — APPROVED** [review]
Works beautifully, pending code simplification changes.

**Comment by swashbuck** [comment]
> Works beautifully, pending code simplification changes.

Thanks, @oliverfoster . I've committed your changes.

**Review by oliverfoster — APPROVED** [review]
