### PR TITLE
Fix: Convert template to JSX (fixes #89)

### LINKED ISSUE #89: Convert template to JSX

### PR DESCRIPTION
**Pull request by swashbuck**
Fixes #89 

### Fix
* Adds **.jsx template** and removes .hbs template
* Removes `resources_force_download` helper. The `download` HTML property is now widely supported: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a#browser_compatibility  Do we still need to support IE or older mobile OS versions?
* Moved **helper functions** to the .jsx template and removed the helper JS file. As far as I know, these functions were not used by any other plugins.  So, they shouldn't need to be registered as Handlebars helpers that can be accessed outside this plugin.

### CODE REVIEW

**Comment by chris-steele** [comment]
IE11 support has been dropped in most cases, but the framework and core plugin GH pages still state support for IE11. N.B. https://www.adaptlearning.org/index.php/documentation/ links to [spec ](https://github.com/adaptlearning/documentation/blob/master/01_cross_workstream/developer_requirements.md) which is very much out of date!

**Review by chris-steele — COMMENTED** [review]
Great job @swashbuck, my only comment is that for a full conversion `onFilterClicked` should be incorporated into your React component.

**Comment by swashbuck** [comment]
Thanks, @chris-steele .  I've moved the event to the template and added the resourcesForceDownload() helper since this needs to support IE11.

File: templates/resources.jsx [hunk 1]
```diff
@@ -0,0 +1,121 @@
+import React from 'react';
+import Adapt from 'core/js/adapt';
+import device from 'core/js/device';
+import { classes, templates } from 'core/js/reactHelpers';
+
+export default function Resources (props) {
+  const {
+    model,
+    resources,
+    onFilterClicked
```
Comment (chris-steele) [inline templates/resources.jsx:10]: @swashbuck I was thinking that the definition of `onFilterClicked` would move here and you'd [use state](https://reactjs.org/docs/hooks-state.html) to keep track of what was currently selected - then you can remove those DOM manipulations (adding/removing classes, attributes etc) and let React handle that.

File: templates/resources.jsx [hunk 2]
```diff
@@ -42,6 +44,36 @@ export default function Resources (props) {
...
+    const $clickedButton = this.$(e.currentTarget);
+    const type = $clickedButton.data('filter');
+
+    updateSelectedType(type);
+
+    // const clickedTabId = $clickedButton.attr('id');
+
+    // this.$('.js-resources-filter-btn-click').removeClass('is-selected').attr('aria-selected', false);
+
+    // $resources.attr('aria-labelledby', clickedTabId);
```
Comment (chris-steele) [inline templates/resources.jsx:59]: `aria-labelledby` is no longer updated

File: templates/resources.jsx [hunk 3]
```diff
@@ -42,6 +44,36 @@ export default function Resources (props) {
...
+    if (e && e.preventDefault) e.preventDefault();
+
+    const $clickedButton = this.$(e.currentTarget);
+    const type = $clickedButton.data('filter');
+
+    updateSelectedType(type);
+
+    // const clickedTabId = $clickedButton.attr('id');
+
+    // this.$('.js-resources-filter-btn-click').removeClass('is-selected').attr('aria-selected', false);
```
Comment (chris-steele) [inline templates/resources.jsx:57]: `aria-selected` is no longer updated

File: templates/resources.jsx [hunk 4]
```diff
@@ -42,6 +44,36 @@ export default function Resources (props) {
...
+    //   items = this.$('.js-resources-item').removeClass('u-display-none');
+    // } else {
+    //   this.$('.js-resources-item')
+    //     .removeClass('u-display-none').not('.is-' + filter)
+    //     .addClass('u-display-none');
+    //   items = this.$('.js-resources-item.is-' + filter);
+    // }
+
+    // if (items.length < 0) return;
+    // a11y.focusFirst($(items[0]));
```
Comment (chris-steele) [inline templates/resources.jsx:74]: does `a11y.focusFirst` need to be called?

**Review by chris-steele — CHANGES_REQUESTED** [review]

File: templates/resources.jsx (hunk 4 above)
Comment (swashbuck) [reply templates/resources.jsx:74]: Thanks, Chris.  Sorry, my last push was a work in progress, and then I was out on PTO on Friday.  I'll pick this back up shortly.

**Comment by swashbuck** [comment]
@chris-steele I seem to have a problem getting a11y.focusFirst to work.  Should I be using a ref hook or am I not using a11y.focusFirst properly?

Aside from that, do you think it would be worthwhile to make a new React component type for each `resources__filter-btn`?  That would reduce the amount of repeated code.

File: templates/resources.jsx [hunk 5]
```diff
@@ -54,17 +54,15 @@ export default function Resources (props) {
...
-    // a11y.focusFirst($items);
+    let $items;
+    if (filter === 'all') {
+      $items = $('.resources__item');
+    } else {
+      $items = $('.resources__item.is-' + filter);
+    }
+
+    if ($items.length < 0) return;
+    a11y.focusFirst($items);
```
Comment (chris-steele) [inline templates/resources.jsx:65]: Because the state is updated React will re-render the component and so $items will be recreated. Therefore you'll need to move this call into a `useEffect` hook.

**Comment by chris-steele** [comment]
You could create a child component for the buttons 👍

**Comment by chris-steele** [comment]
@oliverfoster @cahirodoherty-learningpool @eleanor-heath @joe-allen-89 I'm hearing internally that we aren't supporting IE11 anymore in Adapt, can anyone way in on this?

**Comment by cahirodoherty-learningpool** [comment]
> @oliverfoster @cahirodoherty-learningpool @eleanor-heath @joe-allen-89 I'm hearing internally that we aren't supporting IE11 anymore in Adapt, can anyone weigh-in on this?

Hi Chris, yeah it's my understanding that we we no longer officially support IE11, but we can allow support of it as an override setting. I think anything IE specific can/should be dropped going forward.

**Comment by swashbuck** [comment]
I've created child components for the filter buttons and resource items.

I've also introduced a resourceTypes array that contains the filter categories.  This should make it easier to add new categories if necessary.  One of our clients likes to have several custom categories and doesn't use the default ones (document, link, media).  This also reduces code repetition as the filter button component only appears once in the code.

**Review by chris-steele — APPROVED** [review]

File: templates/resourcesFilterButton.jsx [hunk 6]
```diff
@@ -0,0 +1,38 @@
...
+    resources,
+    selected,
+    _filter
+  } = props;
+
+  const buttonText = model._filterButtons[_filter];
+  const ariaLabel = model._filterAria[`${_filter}Aria`];
+
+  function resourcesHasType(resources, type) {
+    const hasType = resources.some(_.matcher({ _type: type }));
```
Comment (cahirodoherty-learningpool) [inline templates/resourcesFilterButton.jsx:17]: Minor: you can just return this rather than setting a variable

**Review by cahirodoherty-learningpool — APPROVED** [review]
👀

File: templates/resourcesFilterButton.jsx (hunk 6 above)
Comment (swashbuck) [reply templates/resourcesFilterButton.jsx]: Agreed and updated.

**Review by cahirodoherty-learningpool — APPROVED** [review]
👀

**Review by oliverfoster — APPROVED** [review]
